export const BACKEND_BASE_URL_DI_TOKEN = 'BACKEND_BASE_URL_DI_TOKEN';
export const WEB3_CONTRACT_TOOLKIT_DI_TOKEN = 'WEB3_CONTRACT_TOOLKIT_DI_TOKEN';
export const IMAGE_UPLOAD_MAX_SIZE_DI_TOKEN = 'IMAGE_UPLOAD_MAX_SIZE_DI_TOKEN';
export const GLOBALS_SERVICE_PROVIDER_DI_TOKEN = 'GLOBALS_SERVICE_PROVIDER_DI_TOKEN';